version: '3.7'

services:
  apache:
    build: .docker/apache
    container_name: ${PROJECT_NAME}_apache
    ports:
      - ${PROJECT_PORT}:80
    volumes:
      - .:/var/www/app:cached
    depends_on:
      - php
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - ${PROJECT_PORT}:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: EVHEayI6axNl0Z8k
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - ${PROJECT_PORT}:80
    links:
      - mysql
    networks:
      - backend

  php:
    build:
      context: .docker/php
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    container_name: ${PROJECT_NAME}_php
    volumes:
      - .:/var/www/app:cached
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
